frontend:
  containers:
    image: slack-webhook-frontend:latest

  ingress:
    ingressClassName: kong
    host: null

backend:
  containers:
    image: slack-webhook-backend:latest

postgres:
  envVars:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: blog_db
