apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.containers.image | quote }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cockroachdb-credentials
                  key: password
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-url
                  key: url
          volumeMounts:
            - name: cert-volume
              mountPath: /root/.postgresql
              readOnly: true
      volumes:
        - name: cert-volume
          configMap:
            name: certificate-configmap
